from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from skill_utils import display_engine_range, load_json, parse_frontmatter, repository_root

CATEGORY_NAMES = {
    "routing": "Routing",
    "project": "Project Setup",
    "source": "Source Research",
    "architecture": "Architecture",
    "cpp": "C++ and Reflection",
    "build": "Modules and Build Rules",
    "blueprint": "Blueprint",
    "editor": "Editor Automation",
    "quality": "Quality and Performance",
    "delivery": "Build and Delivery",
    "compatibility": "Compatibility",
    "mcp": "UE5.8 MCP",
}


def render(root: Path) -> str:
    manifest = load_json(root / "MANIFEST.json")
    groups: dict[str, list[dict[str, object]]] = defaultdict(list)

    for entry in manifest["skills"]:
        skill_path = root / "skills" / entry["name"] / "SKILL.md"
        metadata, _ = parse_frontmatter(skill_path)
        item = dict(entry)
        item["description"] = metadata["description"]
        groups[str(entry["category"])].append(item)

    lines = [
        "# Skill Catalog",
        "",
        "> Generated by `python scripts/generate_catalog.py`; do not edit by hand.",
        "",
        f"Project version: `{manifest['project_version']}`",
        "",
        f"Minimum engine: `UE {manifest['minimum_engine']}+`",
        "",
        f"Verified engine: `UE {manifest['verified_engine']['version']}` at `{manifest['verified_engine']['commit'][:12]}`",
        "",
        "Load the matching domain skill directly; use [`ue5-router`](skills/ue5-router/SKILL.md) for ambiguous or cross-domain tasks.",
        "",
    ]

    ordered_categories = list(CATEGORY_NAMES)
    for category in ordered_categories:
        items = groups.get(category, [])
        if not items:
            continue
        lines.extend([
            f"## {CATEGORY_NAMES[category]}",
            "",
            "| Skill | Engine | Trigger |",
            "|---|---:|---|",
        ])
        for item in sorted(items, key=lambda value: str(value["name"])):
            name = str(item["name"])
            engine = display_engine_range(str(item["min_engine"]), item.get("max_engine"))
            description = str(item["description"]).replace("|", "\\|")
            lines.append(f"| [`{name}`](skills/{name}/SKILL.md) | `{engine}` | {description} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the deterministic Skill catalog.")
    parser.add_argument("--check", action="store_true", help="Fail if CATALOG.md is not current.")
    parser.add_argument("--root", type=Path, default=repository_root())
    args = parser.parse_args()

    expected = render(args.root)
    output = args.root / "CATALOG.md"
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != expected:
            print("CATALOG.md is stale; run python scripts/generate_catalog.py")
            return 1
        print("CATALOG.md is current")
        return 0

    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
